function clicks() {
    $('#div1').hide();
    $('#div2').show();
    $('#div2').addClass("fadeinv2");
        
    var typed = new Typed('.katakata', {
        strings: ["happy 24th sayang", "Selamat ulang tahun sayang", "aku berdoa semoga", "apa yang kamu perjuangin selama ini berbuah manis", "aku selalu berdoa", "supaya kamu diberi kesehatan fisik dan mental", "aku sangat berharap kamu sembuh sepenuhnya dari penyakitmu", "walaupun aku baru sebentar di hidupmu", "tapi kamu udah jadi bagian dari ceritaku", "jangan pernah merasa sendiri ya", "aku selalu ada disini", "walaupun suatu saat nanti", "kita udah sama-sama jauh karena alasan tertentu", "aku tetap disini", "menepati kata-kataku", "aku sengaja buat ini", "kalau seandainya apa yang aku takutin itu terjadi", "aku tetap bisa inget sama kamu", "kita ga pernah tau tujuan Tuhan mempertemukan kita dengan orang lain itu apa", "yang pasti aku disini buat kamu", "cuma itu yang bisa aku lakuin sejauh ini", "aku mau bilang makasih ke kamu", "makasih udah mau ngeladenin aku sejauh ini", "udah mau nerima", "mungkin sifat buruk aku", "sifat ngeselin aku", "yang mungkin emang aku ga sengaja luapin ke kamu", "aku ga berharap apa-apa sama kamu", "ga berekspetasi apapun tentangmu", "jadi kalau suatu saat emang kita dipertemukan", "jadi dirimu sepenuhnya aja", "aku suka kamu apa adanya", "aku sayang kamu gimanapun kondisimu", "pasti kamu berpikir", "apa sih nih berondong belum pernah ketemu aja", "udah sayang-sayangan", "jujur aku gatau", "dan aku gabisa ke sembarang orang buat bilang sayang", "mau secantik apapun orang itu", "sedeket gimanapun sama orang itu", "maafin aku ya", "kalau emang aku mungkin pernah atau bahkan sering", "ngelewatin batas-batas yang kamu buat", "maafin kalau emang suka buat kamu kesel", "atau aku nya suka maksa", "aku minta maaf", "kalau emang aku ngelakuin kesalahan di mata kamu", "bilang aja ya", "tegur aja akunya", "komunikasiin ke aku", "daripada kamu harus tiba-tiba berubah dan pergi", "aku tau kok setiap orang itu datang dan pergi dihidup kita", "tapi aku ga siap buat kehilangan sesuatu", "apalagi orang yang emang ku sayang", "kamu tau ga sih", "bisa kenal dan dekat sama kamu udah termasuk hal yang istimewa bagi aku", "hubungi aku kalau ada apa-apa ya", "hubungi aku kalau butuh apa-apa", "cerita ke aku", "kalau emang sebelumnya kamu pendam sesuatu karena gabisa cerita", "sekarang kamu bisa", "jadikan aku rumahmu", "pulang ke aku", "ceritain semua keluh kesahmu", "sekarang kamu ada aku yang siap nerima semua cerita dan keluh kesahmu", "jangan berlarut dalam stressmu ya", "ayo kita lewati bareng-bareng!", "AKU BANGGA SAMA KAMU <3", "I LOVE YOU TO THE MOON AND BACK"],
        typeSpeed: 70
    });
}
