function clicks() {
    $('#div1').hide();
    $('#div2').show();
    $('#div2').addClass("fadeinv2");
        
    var typed = new Typed('.katakata', {
        strings: ["Selamat ulang tahun sayang", "walaupun aku baru sebentar dihidupmu", "tapi kamu udah jadi bagian dari ceritaku", "aku berdoa semoga", "apa yang kamu perjuangin selama ini berbuah manis", "kamu selalu diberi kesehatan fisik dan mental", "dan aku sangat berharap kamu sembuh sepenuhnya dengan penyakitmu", "jangan pernah merasa kalau kamu sendirian ya", "aku selalu ada disini kok", "walaupun suatu saat kita udah sama-sama jauh dengan alasan tertentu", "aku sengaja buat ini biar kalau apa yang aku takutin tadi terjadi", "aku bisa inget kamu atau malah sebaliknya", "aku disini buat kamu", "aku juga mau bilang makasih", "gatau sih mau bilang makasih karena apa", "tapi aku mau bilang makasih karena udah mau ngeladenin aku sejauh ini", "aku ga berharap apa-apa sama kamu", "karena kupikir bisa kenal dan dekat sama kamu udah termasuk hal yang istimewa bagi aku", "make it flow aja", "aku juga gapernah berekspetasi apapun tentangmu", "jadi jangan berpikir kalau kamu ga akan sesuai dengan ekspetasiku", "aku sayang kamu gimanapun kondisimu", "pasti berpikir", "apa sih nih berondong belum pernah ketemu udah sayang-sayangan aja", "ya gatau aku juga", "karena ini adanya dan aku ga mudah buat bilang sayang ke orang lain", "mau dia sebaik atau secantik apapun", "kalau apa yang aku rasakan ga kayak gitu", "aku juga mau minta maaf", "kalau emang selama sama aku", "aku buat kamu kesel", "aku ngejengkelein", "terus suka ngelewatin batas-batas yang kamu buat", "atau aku suka maksa", "aku minta maaf ya", "ngomong aja keaku", "cerita ke aku", "daripada kamu harus berubah dan tiba-tiba pergi", "aku tau setiap orang itu datang dan pergi", "tapi aku ga siap buat kehilangan lagi", "kehilangan orang yang emang selama ini ngisi hari-hariku", "hubungi aku kalau ada apa-apa ya", "jadiin aku rumahmu", "pulang ke aku", "cerita ke aku", "ceritain semua keluh kesahmu", "jangan suka pendam sesuatu ya", "kalau emang sebelumnya kamu pendam sesuatu karena gabisa cerita", "kamu ada aku sekarang", "buat nerima semua cerita dan keluh kesahmu", "yang kamu harus tau", "ini adalah 1 dari 2 hal yang aku siapin buat kamu", "di hal kedua ada pertanyaan yang emang sebenarnya kamu harus jawab", "cuma karena aku gamau maksa kamu", "senyamanmu aja", "happy 24th sayang", "AKU BANGGA SAMA KAMU!", "jangan berlarut dalam streesmu", "ayo kita lewati bareng-bareng!", "I LOVE YOU TO THE MOON AND BACK"],
        typeSpeed: 70
    });
}
